### ISSUE TITLE
Cannot connect jira project to github repository from ToolChain Page

### ISSUE THREAD

**Issue by bulbulbhojpuri** [atlassian/github-for-jira#1225]
Saw a similar Issue: #981 except that I have created an organisation and a simple private repo in it and it shows a blank page while connecting.

1) Using the free plan for both Jira Cloud and Github.

2) Installed the "Github for Jira" App & the "Atlassian Jira App" in GitHub and connected them.

![image](https://user-images.githubusercontent.com/102359122/170998752-96de8888-d162-41c9-bf62-d66018d9713d.png)

3) Created an organisation in GH and created a simple private repo for testing.

4) Created a scrum template, team managed project in Jira.

5) But somehow at this stage, The Project cannot connect to a GH Repo. At this screen Project --> ToolChain 

![image](https://user-images.githubusercontent.com/102359122/170998878-d1f20f29-3278-4fb3-8704-937c500c6180.png)

6) If I click on the "Github Link", a new tab opens and it shows a blank page. (I refreshed both the GH and Jira website and tried but still same blank page when connecting).

7) The URL of the blank page is below.

[https://id.atlassian.com/outboundAuth/finish?code=2662c10b442d188512fc&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250YWluZXJJZCI6IjhjMzdiM2U3LWQ3NjItNDVlNi1hNmUyLWE0YzkwMzRjMzJmYl8yMjI3MmZjNS1jZjI3LTQxYmMtYjBiZC04NjVkYjNmNTdhYTgiLCJzZXJ2aWNlS2V5IjoiZ2l0aHViIiwiYWFJZCI6IjYwMjM2NTljNjkyZGExMDA3MGVhYzlmZCIsInJlZGlyZWN0VXJsIjoiaHR0cHM6Ly9wb3B1cC8iLCJzY29wZXMiOlsicHVibGljX3JlcG8iLCJyZWFkOm9yZyIsInJlcG8iXSwiaWF0IjoxNjUzOTE0OTU2LCJleHAiOjE2NTM5MTg1NTYsImlzcyI6IjkxZTNkY2VkLWI4NjgtNDBhZS1hMGE3LWMwYj...](https://id.atlassian.com/outboundAuth/finish?code=2662c10b442d188512fc&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250YWluZXJJZCI6IjhjMzdiM2U3LWQ3NjItNDVlNi1hNmUyLWE0YzkwMzRjMzJmYl8yMjI3MmZjNS1jZjI3LTQxYmMtYjBiZC04NjVkYjNmNTdhYTgiLCJzZXJ2aWNlS2V5IjoiZ2l0aHViIiwiYWFJZCI6IjYwMjM2NTljNjkyZGExMDA3MGVhYzlmZCIsInJlZGlyZWN0VXJsIjoiaHR0cHM6Ly9wb3B1cC8iLCJzY29wZXMiOlsicHVibGljX3JlcG8iLCJyZWFkOm9yZyIsInJlcG8iXSwiaWF0IjoxNjUzOTE0OTU2LCJleHAiOjE2NTM5MTg1NTYsImlzcyI6IjkxZTNkY2VkLWI4NjgtNDBhZS1hMGE3LWMwYjM4N2Y4MjFhMiJ9.nvvVLz1zPppJGnArjOc6fEJKi35eR5OlGPg-Otm56-M)
 

8) As a second try, I uninstalled both the connector apps and repos and project and started from scratch but still get the same error.

Any guidance?

Thanks

**Comment by bulbulbhojpuri** [comment]
The blank page just went through about a few minutes ago. Now in the ToolChain Page This is what I get:

![image](https://user-images.githubusercontent.com/102359122/171015190-659ac406-3d89-4553-bcc9-5598cfa81b8b.png)

Also Now I'm getting this screen on the Project --> Code Page

![image](https://user-images.githubusercontent.com/102359122/171015271-8ea38735-4f0f-4096-a8f1-09ed84e3ca02.png)

So repo is detected (I think?) but is not properly connected to the project perhaps?

I have started the GH backfill process again in Jira but it is taking too long to complete for just two issues in the repo:

![image](https://user-images.githubusercontent.com/102359122/171015339-540214e0-e329-4c5d-8b5e-bbac5d1b095b.png)

Am I following the right process? Are the smart commit issues of the right form for Jira to pickup?

Thanks

**Comment by bulbulbhojpuri** [comment]
I also tried to create another scrum, **"company-managed"** JIRA project and a new private Organization repo and connect both. It still ends up in the situation where the repo is detected but not connected and issues not showing up.

![image](https://user-images.githubusercontent.com/102359122/171024043-0e7773b1-0afd-40e2-b768-59ae98257a52.png)

**Comment by joshkay10** [comment]
Hi @bulbulbhojpuri 
Your smart commits are correct assuming they line up with your Jira project.
Looks like the Repo has been found, unsure why you are seeing 0/1 with "Finished".
Could you check your Dev info panel on the Jira card itself and let me know if you have data showing(should look like the image attached). It could be that the 0/1 count is wrong and the data is backfilled.

The earlier issue looks like something with the  permissions went wrong with either GitHub or Jira. Since that looks all clear now? Try another backfill and let me know if the results are different.

<img width="439" alt="Screen Shot 2022-05-31 at 4 16 09 PM" src="https://user-images.githubusercontent.com/3848691/171091719-b61e7e2e-d96f-475d-9799-1989cc9449f2.png">

**Comment by bulbulbhojpuri** [comment]
> unsure why you are seeing 0/1 with "Finished". Could you check your Dev info panel on the Jira card itself and let me know if you have data showing(should look like the image attached). It could be that the 0/1 count is wrong and the data is backfilled.
> 

I did a check on the 0/1 and created another project and another repo to test the detection and connection.  So these are the JS Console outputs for these screens.

![image](https://user-images.githubusercontent.com/102359122/171106124-708921ef-1b31-4d46-90be-618769c9aa80.png)

```javascript
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
     at b.default (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/e97790deb32cbf8ab2822433610c2c21/_/download/contextbatch/js/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/batch.js?locale=en-US:48:209)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Dropdown constructor has been deprecated and will be removed in a future release. Use Dropdown2 instead.   
     at HTMLDocument.<anonymous> (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/e97790deb32cbf8ab2822433610c2c21/_/download/contextbatch/js/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/batch.js?locale=en-US:4225:201)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:40 
        
       AJS's create element functionality has been deprecated since 5.9.0.
No alternative will be provided.
Use document.createElement() or jQuery.parseHTML(), or preferably use a templating library.
a.default @ batch.js?locale=en-US:40
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
     at l (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/5afb61b052c80124cebeda7092403a6b/_/download/contextbatch/js/jira.heritage.critical/batch.js:6:2054)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:238 Failed to run init function: TypeError: removeOldAnalytics is not a function
function() {
    	determineStorageKey();
        setTimeout(bulkPublish, 500);
        removeOldAnalytics();
    }
5batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
deprecation.js:31 
        
       DEPRECATED JS - PopulateParameters has been deprecated since 9.0.0 and will be removed in 10.0.0.  
     at HTMLDocument.<anonymous> (https://github.atlassian.com/public/aui/aui-prototyping.js:101:106837)
D @ deprecation.js:31
2batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
commons.838d69da90b3b568a47c.8.js:261 
        
       IndexedDB timed out.
(anonymous) @ commons.838d69da90b3b568a47c.8.js:261
5batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
7batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
12batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
16batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
17batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
23batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
18batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
11batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
18batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
10batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
12batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
8batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
7batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
14batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
11batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
all.js:43 SIMPLE XDM: auto resize flickering width detected, setting to 100%
7batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
2batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/d2317ad46a6957cd24257d63875dd603/_/download/contextbatch/css/com.atlassian.jira.jira-atlaskit-plugin:overrides-dialogs/adg3-dialog-overrides-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/67162923a396ba0a368a22d6152098fe/_/download/contextbatch/css/jira.webresources:key-commands,jira.webresources:header,com.atlassian.administration.atlassian-admin-quicksearch-jira:admin-quicksearch-webresources,jira.webresources:global-static,com.atlassian.jira.plugins.jira-development-integration-plugin:repository-shortcuts-navigation-next,com.atlassian.analytics.analytics-client:js-events,com.atlassian.plugins.atlassian-connect-plugin:jira-atlassian-connect-resources-v5,com.atlassian.jira.jira-fileviewer-plugin:atlassian-fileviewer,com.atlassian.jira.jira-issue-nav-plugin:stylesheets,com.atlassian.jira.jira-view-issue-plugin:issuelink-bridge-global-init,com.atlassian.crowd.user-provisioning-vertigo-plugin:impersonation-resources,com.atlassian.jira.jira-atlaskit-plugin:overrides-general,com.atlassian.pas:pas-everypage-static,com.atlassian.auiplugin:dialog2,com.atlassian.jira.jira-atlaskit-plugin:breadcrumbs,com.atlassian.jira.plugins.jira-development-integration-plugin:devsummarycf-resources-init,com.atlassian.jira.plugins.jira-browser-metrics:contrib,com.pyxis.greenhopper.jira:gh-create-board-adg3-no-condition,com.atlassian.plugins.browser.metrics.browser-metrics-plugin:impl,-com.atlassian.jira.jira-quick-edit-plugin:quick-create-issue,-jira.webresources:jira-global,-com.atlassian.auiplugin:aui-spinner,-com.atlassian.jira.plugins.jira-dnd-attachment-plugin:shared-utility,-com.pyxis.greenhopper.jira:gh-view-issue,-jira.create.issue,-jira.webresources:feature-flags,-jira.webresources:dialogs,-jira.webresources:util,-com.atlassian.jira.plugins.jira-wiki-editor:wiki-editor-resources-init,-jira.webresources:util-lite,-com.pyxis.greenhopper.jira:gh-issue-type-whitelist,-jira.webresources:calendar-en,-com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.webresources:skate,-jira.heritage.critical/adg3-breadcrumbs-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/1465f1e3347d7e48c8ac28337ce55631/_/download/contextbatch/css/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/adg3-sidebar-layout-overrides-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
3batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
```

If I click on "Connect Github Organization"

![image](https://user-images.githubusercontent.com/102359122/171106466-60ae7b2d-75c2-4bec-8421-7ed0691eeb71.png)

```javascript
deprecation.js:31 
        
       DEPRECATED JS - PopulateParameters has been deprecated since 9.0.0 and will be removed in 10.0.0.  
     at HTMLDocument.<anonymous> (https://github.atlassian.com/public/aui/aui-prototyping.js:101:106837)
D @ deprecation.js:31
/favicon.ico:1 
   
    Failed to load resource: the server responded with a status of 401 ()

```

**Comment by bulbulbhojpuri** [comment]
> Hi @bulbulbhojpuri Your smart commits are correct assuming they line up with your Jira project. 

1) So what is the proper flow here?  a) create a jira issue with key b) then create a commit with that Jira ID c) and then redo a backfill sequence?

2) Would I be right in thinking that Creating GH issue with Jira Key would not be ported to Jira Issues?

3) Would this GH-Jira issue-commit flow fail if the flow direction is not followed properly?

Because even though I put two commits in the test repo. It is not backfilling in the Code Part.

![image](https://user-images.githubusercontent.com/102359122/171108062-f886c97b-477f-4b9f-8117-92514d5f6197.png)

Is the Code Page supposed to be blank?

![image](https://user-images.githubusercontent.com/102359122/171108631-ad85e36d-3c38-427b-8f38-0e4cd1aaa320.png)

**Comment by bulbulbhojpuri** [comment]
> Hi @bulbulbhojpuri Could you check your Dev info panel on the Jira card itself and let me know if you have data showing(should look like the image attached). It could be that the 0/1 count is wrong and the data is backfilled.
> 

Thanks for pursuing this conversation. I'm just starting out in Jira here.

![image](https://user-images.githubusercontent.com/102359122/171110246-8aee02af-f4e9-4d8c-8940-cdea6d713c93.png)


```javascript
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
     at b.default (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/e97790deb32cbf8ab2822433610c2c21/_/download/contextbatch/js/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/batch.js?locale=en-US:48:209)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Dropdown constructor has been deprecated and will be removed in a future release. Use Dropdown2 instead.   
     at HTMLDocument.<anonymous> (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/e97790deb32cbf8ab2822433610c2c21/_/download/contextbatch/js/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/batch.js?locale=en-US:4225:201)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:40 
        
       AJS's create element functionality has been deprecated since 5.9.0.
No alternative will be provided.
Use document.createElement() or jQuery.parseHTML(), or preferably use a templating library.
a.default @ batch.js?locale=en-US:40
batch.js?locale=en-US:51 
        
       DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
     at l (https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/5afb61b052c80124cebeda7092403a6b/_/download/contextbatch/js/jira.heritage.critical/batch.js:6:2054)
k @ batch.js?locale=en-US:51
batch.js?locale=en-US:238 Failed to run init function: TypeError: removeOldAnalytics is not a function
function() {
    	determineStorageKey();
        setTimeout(bulkPublish, 500);
        removeOldAnalytics();
    }
7batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
commons.838d69da90b3b568a47c.8.js:261 
        
       IndexedDB timed out.
(anonymous) @ commons.838d69da90b3b568a47c.8.js:261
196batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
5batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
3batch.js?locale=en-US:238 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
/rest/api/3/project/JGOW/properties/projectTheme:1 

       Failed to load resource: the server responded with a status of 404 ()
/rest/api/2/project/JGOW/properties/isDevopsProject:1 

       Failed to load resource: the server responded with a status of 404 ()
/rest/api/latest/user/properties/growth-puet-banner-cadence?accountId=6023659c692da10070eac9fd:1 
        
 Failed to load resource: the server responded with a status of 404 ()
vendor~748942c6.e128229823ae3fcfaad3.8.js:208 
        
       [@atlaskit/theme]: The focus ring mixin is deprecated. Please use `@atlaskit/focus-ring` instead.
a @ vendor~748942c6.e128229823ae3fcfaad3.8.js:208
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/1465f1e3347d7e48c8ac28337ce55631/_/download/contextbatch/css/jira.webresources:skate,jira.webresources:dialogs,jira.webresources:jira-global,jira.webresources:util-lite,jira.webresources:util,jira.webresources:feature-flags,com.atlassian.auiplugin:aui-spinner,com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.heritage.critical/adg3-sidebar-layout-overrides-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/67162923a396ba0a368a22d6152098fe/_/download/contextbatch/css/jira.webresources:key-commands,jira.webresources:header,com.atlassian.administration.atlassian-admin-quicksearch-jira:admin-quicksearch-webresources,jira.webresources:global-static,com.atlassian.jira.plugins.jira-development-integration-plugin:repository-shortcuts-navigation-next,com.atlassian.analytics.analytics-client:js-events,com.atlassian.plugins.atlassian-connect-plugin:jira-atlassian-connect-resources-v5,com.atlassian.jira.jira-fileviewer-plugin:atlassian-fileviewer,com.atlassian.jira.jira-issue-nav-plugin:stylesheets,com.atlassian.jira.jira-view-issue-plugin:issuelink-bridge-global-init,com.atlassian.crowd.user-provisioning-vertigo-plugin:impersonation-resources,com.atlassian.jira.jira-atlaskit-plugin:overrides-general,com.atlassian.pas:pas-everypage-static,com.atlassian.auiplugin:dialog2,com.atlassian.jira.jira-atlaskit-plugin:breadcrumbs,com.atlassian.jira.plugins.jira-development-integration-plugin:devsummarycf-resources-init,com.atlassian.jira.plugins.jira-browser-metrics:contrib,com.pyxis.greenhopper.jira:gh-create-board-adg3-no-condition,com.atlassian.plugins.browser.metrics.browser-metrics-plugin:impl,-com.atlassian.jira.jira-quick-edit-plugin:quick-create-issue,-jira.webresources:jira-global,-com.atlassian.auiplugin:aui-spinner,-com.atlassian.jira.plugins.jira-dnd-attachment-plugin:shared-utility,-com.pyxis.greenhopper.jira:gh-view-issue,-jira.create.issue,-jira.webresources:feature-flags,-jira.webresources:dialogs,-jira.webresources:util,-com.atlassian.jira.plugins.jira-wiki-editor:wiki-editor-resources-init,-jira.webresources:util-lite,-com.pyxis.greenhopper.jira:gh-issue-type-whitelist,-jira.webresources:calendar-en,-com.atlassian.jira.jira-atlaskit-plugin:sidebar,-jira.webresources:skate,-jira.heritage.critical/adg3-breadcrumbs-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://d2cq1c601jr99q.cloudfront.net/atl-vertigo--shard-jira-prod-ap-18--4--jres.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/azc3hx/b/7/d2317ad46a6957cd24257d63875dd603/_/download/contextbatch/css/com.atlassian.jira.jira-atlaskit-plugin:overrides-dialogs/adg3-dialog-overrides-min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Node cannot be found in the current page.
```

**Comment by bulbulbhojpuri** [comment]
Closing as unclear where the problem originates. Trying the suggestions of Atlassian community leader below.

Robert Wen COMMUNITY LEADER May 31, 2022

The Code page isn't empty.  It's showing the repos that are connected to Jira and where on the Jira issue you can perform actions such as creating a branch, and creating a pull request.

The integration that you're using allows connection to the Git repo only.  This allows you to do the following:

From a Jira issue, create a branch that has the name of the Jira issue ID
From a Git commit comment, connect the commit to the Jira issue
Create a pull request from a Jira issue.
You can sync GitHub issues with Jira issues, but that involves additional integrations from the Atlassian Marketplace.

You cannot create a Jira issue and "hardwire" the Jira issue ID.  Jira determines the ID
